import { Projet } from './project';
  
export const PROJETS: Projet[] = [
    {
        id: 20,
        nom: "Présentation VSJ Natation",
        domaine: "Montage",
        domaineImg:"assets/img/icone_montage.png",
        imgSrc: "assets/img/Dashboard_VSJ.png",
        description: "Au cours d’un projet de groupe universitaire, j’ai été amené à travailler sur la refonte d’un site de piscine appelé VSJ Natation. Pour faire la présentation des nouvelles fonctionnalités du site, j’ai réalisé une vidéo en motion design avec After Effect. J’ai réalisé deux versions : verticale et horizontale pour adapter la vidéo à tous les médias de diffusions (Youtube, TikTok, Instagram, …).",
        technologie: ["After Effect", " Premiere Pro"],
        images: ["https://youtu.be/A2JB6EZNwoA","https://youtube.com/shorts/A9r1Og5NCeA?feature=share"],
    },
    {
        id: 1,
        nom: "Rendu réaliste",
        domaine: "3D",
        domaineImg:"assets/img/icone_3D.png",
        imgSrc: "assets/img/rendufinal4K.png",
        description: "Afin de m’améliorer dans le domaine de la 3D, je me suis lancé le défi de produire une scène 3D réaliste de A à Z. En m’inspirant de photos trouvées sur Pinterest, j'ai choisi de créer la table d’une maison dans le sud, lors du couché de soleil. J’ai donc modélisé et texturé l’intégralité de la scène moi-même.",
        technologie: ["Blender"],
        images: [],
    },
    {
        id: 2,
        nom: "Site JPO Meaux",
        domaine: "Dev",
        domaineImg:"assets/img/icone_dev.png",
        imgSrc: "assets/img/logo_iut.png",
        description: "Dans le cadre d’un projet de groupe, je me suis chargé de réaliser un site qui pourrait être utilisé dans le cadre de la JPO de l'université Gustave Eiffel de Meaux. Pour cela, nous avons repris la charte graphique de l’IUT, modélisé une salle en 3D puis j’ai développé le site avec Angular et d’autres frameworks.",
        technologie: ["Angular"],
        images: ["https://romain234.github.io/saejpo/"],
    },
    {
        id: 3,
        nom: "Chambre isométrique",
        domaine: "3D",
        domaineImg:"assets/img/icone_3D.png",
        imgSrc: "assets/img/rendu2.png",
        description: "Lors de mon stage, j’ai découvert le style de modélisation isométrique, qui m'a beaucoup plu. Lorsque je suis rentré, j’ai décidé de reproduire ma chambre dans ce style afin de m’exercer.",
        technologie: ["Blender"],
        images: [],
    },
    {
        id: 4,
        nom: "Cartes Cadeaux Roissy Pays de France",
        domaine: "Montage",
        domaineImg:"assets/img/icone_montage.png",
        imgSrc: "assets/img/LeFranklin.jpg",
        description: "Afin de promouvoir des cartes cadeaux offrant 20% de réduction, l’agglomération de Roissy Pays de France souhaitait créer des vidéos pour présenter les commerces partenaires pour mettre en avant les commerçants et les cartes cadeaux. J’ai donc imaginé, filmé, écrit puis monté des vidéos présentant 5 commerces. Pour chaque restaurant, boulangerie et opticien, j’ai réalisé un storyboard afin de savoir comment mettre en avant les spécificités de chaque commerce, que ce soit en images où avec la voix-off.",
        technologie: ["Premiere Pro"],
        images: ["https://www.youtube.com/watch?v=y8KIkqv3kaw", "https://youtu.be/CaHv6yMLoI4","https://youtu.be/K-ck1Wcs5ds","https://youtu.be/GEfRaoAwv_g","https://youtu.be/wieMKStBHAk"],
    },
    {
        id: 5,
        nom: "L'envie gourmande",
        domaine: "Design",
        domaineImg:"assets/img/icone_design.png",
        imgSrc: "assets/img/logo_EG.png",
        description: "Dans le cadre de mon stage, j’ai réalisé un logo pour la boulangerie “L’Envie Gourmande”. L’objectif était de créer un logo simple et moderne, je suis donc parti sur un logo ou le “e” et le “g” se confondent, comme une signature, accompagné du nom de la boulangerie en police cursive. ",
        technologie: ["Illustrator"],
        images: [],
    },
    {
        id: 6,
        nom: "Modélisation Aang",
        domaine: "3D",
        domaineImg:"assets/img/icone_3D.png",
        imgSrc: "assets/img/aang_rendu3.png",
        description: "Pour m’entrainer à modéliser et sculpter des personnages avec Blender, je crée Aang du dessin animé 'Avatar, le dernier maître de l'air'.",
        technologie: ["Blender"],
        images: [],
    },
    {
        id: 7,
        nom: "Cube Clicker",
        domaine: "Dev & Design",
        domaineImg:"assets/img/icone_dev.png",
        imgSrc: "assets/img/grass.png",
        description: "Dans le cadre d’un projet, j’ai réalisé un “Cookie Clicker”, j’ai donc choisi d’en faire un sur le thème de Minecraft. J’ai donc repris plusieurs décors du jeu, les différents éléments puis j’en ai fait une maquette sur Figma. Ensuite j’ai développé le jeu avec Javascript.",
        technologie: ["JS", " Figma"],
        images: [],
    },
    {
        id: 8,
        nom: "Sac d'évacuation",
        domaine: "Montage",
        domaineImg:"assets/img/icone_montage.png",
        imgSrc: "assets/img/illu-sac.png",
        description: "Lors d’un stage, j’ai dû réaliser un film de prévention afin de conseiller au public de préparer un sac d’évacuation. Ce sac doit contenir le nécessaire si l’on doit quitter notre domicile d’urgence (incendie, catastrophe naturelle,etc..). J’ai donc réalisé ce film en motion design avec After Effect et Premiere Pro.",
        technologie: ["After Effect", " Premiere Pro"],
        images: ["https://youtu.be/6Zk1FMDPVQo"],
    },
    {
        id: 9,
        nom: "ChapChapFood",
        domaine: "Design",
        domaineImg:"assets/img/icone_design.png",
        imgSrc: "assets/img/chapchapfood.png",
        description: "Lors de mon stage à l’agglomération de Roissy Pays de France, j’ai avec ChapChap Food, un service traiteur de nourriture de cuisine afro. J’ai utilisé les photos mises à ma disposition et la charte graphique pour réaliser un flyer, une carte de visite et des posts pour Instagram. Après quelques échanges avec la cliente, nous sommes arrivés à ces versions finales.",
        technologie: ["Illustrator", " Photoshop"],
        images: [],
    },
    {
        id: 10,
        nom: "Modélisation Changelin",
        domaine: "3D",
        domaineImg:"assets/img/icone_3D.png",
        imgSrc: "assets/img/changelin2.png",
        description: "Pour m’entrainer à modéliser et sculpter des personnages avec Blender, je crée Changelin du dessin animé “Teen Titans Go”.",
        technologie: ["Blender"],
        images: [],
    },
    {
        id: 11,
        nom: "PGAV",
        domaine: "Montage",
        domaineImg:"assets/img/icone_montage.png",
        imgSrc: "assets/img/illu-pgav.png",
        description: "Lors de mon stage, j’ai dû réaliser un film pour la SNCF où je devais mettre en vidéo un rapport de plusieurs pages sur la maintenance de la voie ferrée. Pour cela j’ai modélisé en 3D les différents éléments et outils du rapport puis j’ai recréé chaque cas du rapport, en intégrant des vidéos que la SNCF avait envoyées. J’ai modélisé les éléments avec Cinema 4D puis je les ai intégrés à After Effect avec le plugin 'element 3D'.",
        technologie: ["After Effect", " Premiere Pro", " Cinema 4D"],
        images: ["https://www.youtube.com/watch?v=6u4W4av5Wg8"],
    },
    {
        id: 12,
        nom: "Modélisation Carapuce",
        domaine: "3D",
        domaineImg:"assets/img/icone_3D.png",
        imgSrc: "assets/img/carapuce_rendu.png",
        description: "Pour m’entrainer à modéliser et sculpter des personnages et scène avec Blender, j’ai recréé en 3D une figurine de Carapuce que l’on m’avait offert.",
        technologie: ["Blender"],
        images: [],
    },
    {
        id: 13,
        nom: "Les bons réflexes",
        domaine: "Montage",
        domaineImg:"assets/img/icone_montage.png",
        imgSrc: "assets/img/illu-debroussailler.png",
        description: "Lors de mon stage, j’ai dû réaliser un film de prévention afin d’informer sur les règles d’entretien sur la végétation, afin de ralentir la propagation des incendies. J’ai donc créé ce film en motion design à l’aide d'illustrations trouvées sur Freepik, puis je les ai animées sur After Effect.",
        technologie: ["After Effect", " Premiere Pro"],
        images: ["https://youtu.be/M7EMrWwFf8A"],
    },
    {
        id: 14,
        nom: "Maquettes Portfolio",
        domaine: "Design",
        domaineImg:"assets/img/icone_design.png",
        imgSrc: "assets/img/icone_all.png",
        description: "Comme avant tout projet de développement, il est important d’avoir une maquette afin de savoir une idée de ce à quoi va ressembler le site. J’ai donc créé plusieurs maquettes avant de faire mon portfolio pour savoir quelle version je choisirai d’utiliser. Pour cela, j’ai utilisé Figma puis j’ai testé plusieurs palettes de couleur et configurations.",
        technologie: ["Figma"],
        images: [],
    },


    
];

export const projetList3D = PROJETS.filter(s=>s.domaine?.includes('3D'));
export const projetListDev = PROJETS.filter(s=>s.domaine?.includes('Dev'));
export const projetListDesign = PROJETS.filter(s=>s.domaine?.includes('Design'));
export const projetListMontage = PROJETS.filter(s=>s.domaine?.includes('Montage'));

